version: 2

models:
  - name: stg_raw_messages
    description: "Cleaned staging model for raw messages"
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel
        tests:
          - not_null
      - name: cleaned_text
        tests:
          - not_null

  - name: dim_channels
    description: "Dimension table for channel analytics"
    columns:
      - name: channel
        tests:
          - unique
          - not_null
